baseURL = 'https://enchanter.ai"'
languageCode = 'en-us'
title = "Shervin Sahba"
theme = "hugo-theme-monochrome"
paginate = 5


[Author]
    name = "Shervin Sahba"
    bio = "Shervin Sahba is a real human being and totally not an extra-terrestrial nor cybernetic construct."

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[markup.goldmark.renderer]
    unsafe = false
