baseURL = 'https://enchanter.ai"'
languageCode = 'en-us'
title = "Shervin Sahba"
theme = "hugo-theme-monochrome"
paginate = 5


[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[markup.goldmark.renderer]
    unsafe = false
