[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  parent = ""
  weight = 1
[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  parent = ""
  weight = 2
[[navbar]]
  identifier = "CV"
  name = "CV"
  url = "/about/#cv?"
  parent = ""
  weight = 3
